source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
target 'HCJD-User' do
pod 'AFNetworking'
pod 'SDCycleScrollView'
pod 'SDAutoLayout'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'AMapLocation'
pod 'AMap2DMap'
pod 'AMapSearch'
pod 'DZNEmptyDataSet'
pod 'TPKeyboardAvoiding'
end
